// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiSqlite.Data;

#nullable disable

namespace WebApiSqlite.Migrations
{
    [DbContext(typeof(WebApiSqliteContext))]
    [Migration("20220927105335_AddEcologic")]
    partial class AddEcologic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("WebApiSqlite.Models.Developer", b =>
                {
                    b.Property<int>("DeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ECOCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ECOSelected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ECOYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeveloperId");

                    b.ToTable("Developers");
                });
#pragma warning restore 612, 618
        }
    }
}
